Vagrant.require_version ">= 1.7.0"

Vagrant.configure("2") do |config|
  config.vm.box = "f25-cloud-based"
  config.vm.box_url = "http://fedora.mirrors.pair.com/linux/releases/25/CloudImages/x86_64/images/Fedora-Cloud-Base-Vagrant-25-1.3.x86_64.vagrant-virtualbox.box"

  # AVOID PROBLEMS HAVING A DIFF IP PER VM RUNNING
  config.vm.network :private_network, ip: "33.33.33.103"

  # AVOID PROBLEMS HAVING A DIFF HOSTNAME BY VM RUNNING
  config.vm.hostname = "cli-03"

  config.vm.provider :virtualbox do |vbox|
    vbox.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo dnf install openssl -y
    sudo useradd myuser -p "$(openssl passwd mypwd)" -m
    echo "myuser ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/90-cloud-init-users

  SHELL

end
