Vagrant.require_version ">= 1.7.0"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  # Specify a box version for our own sanity
  config.vm.box_version = "20170119.1.0"

  # AVOID PROBLEMS HAVING A DIFF IP PER VM RUNNING
  config.vm.network :private_network, ip: "33.33.33.102"

  # AVOID PROBLEMS HAVING A DIFF HOSTNAME BY VM RUNNING
  config.vm.hostname = "cli-02"

  config.vm.provider :virtualbox do |vbox|
    vbox.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update

    #sudo useradd myuser -G sudo -m -p mypwd
    #sudo useradd -p "$(openssl passwd mypwd)" myuser
    sudo useradd myuser -p "$(openssl passwd mypwd)" -m -G sudo
    echo "myuser ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/90-cloud-init-users

  SHELL

end
