---
  - name: Copy check_security_update plugin to Nagios3 server
    template: src=check_security_updates.py
      dest=/usr/lib/nagios/plugins/check_security_updates
      mode='a+x'

  - name: Give Nagios user permission to sudo
    lineinfile: path=/etc/sudoers.d/90-cloud-init-users
      line='nagios ALL=(ALL) NOPASSWD:ALL'
