Vagrant.require_version ">= 1.7.0"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  # Specify a box version for our own sanity
  config.vm.box_version = "20170119.1.0"

  # AVOID PROBLEMS HAVING A DIFF IP PER VM RUNNING
  config.vm.network :private_network, ip: "33.33.33.100"

  # AVOID PROBLEMS HAVING A DIFF HOSTNAME BY VM RUNNING
  config.vm.hostname = "nagios-server"

  config.vm.provider :virtualbox do |vbox|
    vbox.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update

    # Install Nagios
    sudo DEBIAN_FRONTEND=noninteractive apt install -y nagios3 nagios-nrpe-plugin

    # To create Nagios users
    sudo htpasswd -b -c /etc/nagios3/htpasswd.users nagiosadmin NAGIOS_PWD

    # Update password of Nagios user
    # sudo htpasswd -b /etc/nagios3/htpasswd.users nagiosadmin NEW_NAGIOS_PWD

    ############################
    ### Create custom plugin ###
    ############################
    sudo touch /usr/lib/nagios/plugins/check_local_restart_required
    echo "#!/usr/bin/env python3

import os, socket

def check_restart_required():
    if os.path.exists('/var/run/reboot-required'):
        print('*** System restart required *** ')
        exit(2)
    print('OK, no system restart needed')
    exit(0)


if __name__ == '__main__':
    check_restart_required()" | sudo tee /usr/lib/nagios/plugins/check_local_restart_required
    ############################
    #### End creating plugin ###
    ############################

    # Fix permission of plugin
    sudo chmod a+x /usr/lib/nagios/plugins/check_local_restart_required

    # Enable command check_local_restart_required to use our custom plugin
    echo "
# 'check-restart-required'
define command{
  command_name  check_local_restart_required
  command_line  /usr/lib/nagios/plugins/check_local_restart_required 
}
" | sudo tee -a /etc/nagios3/commands.cfg

    # Add check_local_restart_required service check to Nagios3 server(localhost)
    echo "
# Custom check for system restart required.
define service{
        use                             generic-service         ; Name of service template to use
        host_name                       localhost
        service_description             System Restart Required
                check_command                   check_local_restart_required
        }" | sudo tee -a /etc/nagios3/conf.d/localhost_nagios2.cfg

    # Restart Nagios3 service
    sudo service nagios3 restart

  SHELL

end
